language: node_js
install:
- npm install
node_js:
- node
script:
- npm run build
deploy:
  provider: npm
  email: mail.raman.s@gmail.com
  api_key:
    secure: XBT1H6PL1ENchtXYL8WdlqSQSrq8KyNXYltxWgnja0RPU6NfYKaOH64o9ZilLRbIc1Z5XDtnfAWISONmn+101Zk3X6aiHMoeeyJWYIYx20Zxl2At/IkBnjDAvJ4nu9hvjczcY8gVp507M0CDgjTvxNIw6xkz9i8+ZWubBdR9wxbHPXgHP8XKb0MyMAsvC2VnySzxx8IibBQ/zp+RjNebecPnMF4TCh5avoY7/VSlvBQXtj/hmRwvIr8yi4tMPyMk8lfPh3mak0M66/hzL6PJLgTWjdcF3ke1SCMyKvHpqSmqR81frVk88wgCLl1pw2t6t32OlQhZSkBiM7xquyG4lH24R7cWetVknwQgC/dRwMbfdyXeLdnksX46NeJn/hs4naR3zu1hSTy4KzuUjsZV7rrV2fXsKaBBrcgCmZ4/ENk/mY7QwroiAFBZmZlkbgZUjTYgJRg2uuk2TJjzQbRmdA8JFaglRCFtkym0RX+xXOOp5Pba2F/HOKy8woPNJ293jN6/IUZJw27ob1ecXWGmOq4gxt7jQZ9RIIRPYzvrjqGf1EmAoj33RdHxjRgMHILI+N5OTGypq3r3iDQUg9oCXh6fCBGN3xg+8305HNHYjVib8gXhNHIiNnEOaiiXU1AASIzw3SR/vVrVEC7l5nNNA2XPuF3lP57w1YoDyHKqC6Q=
  on:
    tags: true
    branch: master
  skip_cleanup: true
